# column names:
# in 2020 two additional columns were added to the original list of columns:
# ReporterId & Timestamp. Thus depending on the year there might be 24 or 26
# fields

cont_cols_names_pre2022 = [
    "FilerID",
    "EYear",
    "Cycle",
    "Section",
    "Contributor",
    "Address1",
    "Address2",
    "City",
    "State",
    "Zipcode",
    "occupation",
    "Ename",
    "EAddress1",
    "EAddress2",
    "ECity",
    "EState",
    "EZipcode",
    "ContDate1",
    "ContAmt1",
    "ContDate2",
    "ContAmt2",
    "ContDate3",
    "ContAmt3",
    "ContDesc",
]

cont_cols_names_post22 = [
    "FilerID",
    "ReporterID",
    "Timestamp",
    "EYear",
    "Cycle",
    "Section",
    "Contributor",
    "Address1",
    "Address2",
    "City",
    "State",
    "Zipcode",
    "occupation",
    "Ename",
    "EAddress1",
    "EAddress2",
    "ECity",
    "EState",
    "EZipcode",
    "ContDate1",
    "ContAmt1",
    "ContDate2",
    "ContAmt2",
    "ContDate3",
    "ContAmt3",
    "ContDesc",
]

filer_cols_names_pre2022 = [
    "FilerID",
    "EYear",
    "Cycle",
    "Amend",
    "Terminate",
    "FilerType",
    "FilerName",
    "Office",
    "District",
    "Party",
    "Address1",
    "Address2",
    "City",
    "State",
    "Zipcode",
    "County",
    "PHONE",
    "BEGINNING",
    "MONETARY",
    "INKIND",
]

filer_cols_names_post2022 = [
    "FilerID",
    "ReporterID",
    "Timestamp",
    "EYear",
    "Cycle",
    "Amend",
    "Terminate",
    "FilerType",
    "FilerName",
    "Office",
    "District",
    "Party",
    "Address1",
    "Address2",
    "City",
    "State",
    "Zipcode",
    "County",
    "PHONE",
    "BEGINNING",
    "MONETARY",
    "INKIND",
]
cont_year_dtypes = {
    "FilerID": str,
    "ReporterID": str,
    "Timestamp": object,
    "EYear": int,
    "Cycle": object,
    "Section": object,
    "Contributor": str,
    "Address1": str,
    "Address2": str,
    "City": str,
    "State": str,
    "Zipcode": object,
    "occupation": str,
    "Ename": str,
    "EAddress1": str,
    "EAddress2": str,
    "ECity": str,
    "EState": str,
    "EZipcode": str,
    "ContDate1": object,
    "ContAmt1": float,
    "ContDate2": object,
    "ContAmt2": float,
    "ContDate3": object,
    "ContAmt3": float,
    "ContDesc": object,
}
filer_year_dypes = {
    "FilerID": str,
    "ReporterID": str,
    "Timestamp": object,
    "EYear": int,
    "Cycle": int,
    "Amend": object,
    "Terminate": object,
    "FilerType": object,
    "FilerName": str,
    "Office": str,
    "District": str,
    "Party": str,
    "Address1": str,
    "Address2": str,
    "City": str,
    "State": str,
    "Zipcode": object,
    "County": object,
    "PHONE": object,
    "BEGINNING": object,
    "MONETARY": object,
    "INKIND": object,
}

office_abb_dict = {
    "GOV": "Governor",
    "LTG": "Liutenant Gov",
    "ATT": "Attorney General",
    "AUD": "Auditor General",
    "TRE": "State Treasurer",
    "SPM": "Justice of the Supreme Crt",
    "SPR": "Judge of the Superior Crt",
    "CCJ": "Judge of the CommonWealth Crt",
    "CPJ": "Judge of the Crt of Common Pleas",
    "MCJ": "Judge of the Municipal Crt",
    "TCJ": "Judge of the Traffic Crt",
    "STS": "Senator (General Assembly)",
    "STH": "Rep (General Assembly)",
    "OTH": "Other(local offices",
}
