
fossil_fuel_organizations: 
  - exxon
  - chevron
  - southwest gas
  - petroleum
  - koch industries
  - koch companies
  - oil & gas
  - marathon oil
  - shell oil
  - koch industries
  - koch pac
  - kochpac
  - southwest gas az
  - pinnacle west
  - americans for prosperity
  - energy transfer

clean_energy_organizations:
  - clean energy
  - vote solar action
  - renewable
  - pattern energy
  - beyond carbon
  - lcv victory
  - league of conservation