base:
  state_code: PA
  read_csv_params:
    sep: ","
    encoding: latin-1
    on_bad_lines: warn
  state_code_columns:
    - reported_state
  year_filter_filepath_regex: ".*\\/(\\d{4})\\/[^\\/]+$"


contributions:
  inherits: base
  table_name: Transaction
  column_details:
    - raw_name: CampaignFinanceID
      type: str

    - raw_name: FILERID
      type: str
      standard_name: recipient_id

    - raw_name: EYEAR
      type: Int16
      standard_name: reported_election_year

    - raw_name: SubmittedDate
      type: str

    - raw_name: CYCLE
      type: str

    - raw_name: Section
      type: str

    - raw_name: CONTRIBUTOR
      type: str
      standard_name: donor--full_name

    - raw_name: ADDRESS1
      type: str
      standard_name: donor--address--line_1

    - raw_name: ADDRESS2
      type: str
      standard_name: donor--address--line_2

    - raw_name: CITY
      type: str
      standard_name: donor--address--city

    - raw_name: STATE
      type: str
      standard_name: donor--address--state

    - raw_name: ZIPCODE
      type: str
      standard_name: donor--address--zipcode

    - raw_name: OCCUPATION
      type: str
      standard_name: donor--employer--role

    - raw_name: ENAME
      type: str
      standard_name: donor--employer--organization--full_name

    - raw_name: EADDRESS1
      type: str
      standard_name: donor--employer--organization--address--line_1

    - raw_name: EADDRESS2
      type: str
      standard_name: donor--employer--organization--address--line_2

    - raw_name: ECITY
      type: str
      standard_name: donor--employer--organization--address--city

    - raw_name: ESTATE
      type: str
      standard_name: donor--employer--organization--address--state

    - raw_name: EZIPCODE
      type: str
      standard_name: donor--employer--organization--address--zipcode

    - raw_name: CONTDATE1
      type: Int32
      date_format: "%Y%m%d"
      standard_name: date-1

    - raw_name: CONTAMT1
      type: Float32
      standard_name: amount-1

    - raw_name: CONTDATE2
      type: Int32
      date_format: "%Y%m%d"
      standard_name: date-2

    - raw_name: CONTAMT2
      type: Float32
      standard_name: amount-2

    - raw_name: CONTDATE3
      type: Int32
      date_format: "%Y%m%d"
      standard_name: date-3

    - raw_name: CONTAMT3
      type: Float32
      standard_name: amount-3

    - raw_name: CONTDESC
      type: str
      standard_name: description
  
contributions_post_2023:
  inherits: contributions
  path_pattern: "(?i)^(?:20(?:2[4-9]|[3-9]\\d))/contrib.*\\.txt$"

contributions_2023:
  inherits: contributions
  read_csv_params:
    sep: ","
    encoding: latin-1
    on_bad_lines: warn
    header: 0
  path_pattern: "(?i)^2023/contrib.*\\.txt$"


contributions_through_2022:
  inherits: contributions 
  column_order:
    - FILERID
    - EYEAR
    - CYCLE
    - SECTION
    - CONTRIBUTOR
    - ADDRESS1
    - ADDRESS2
    - CITY
    - STATE
    - ZIPCODE
    - OCCUPATION
    - ENAME
    - EADDRESS1
    - EADDRESS2
    - ECITY
    - ESTATE
    - EZIPCODE
    - CONTDATE1
    - CONTAMT1
    - CONTDATE2
    - CONTAMT2
    - CONTDATE3
    - CONTAMT3
    - CONTDESC
 

  valid_years: 2010:2022
  path_pattern: "(?i)^(19[0-9][0-9]|20[0-1][0-9]|2020|2021)/contrib.*\\.txt$"


filer:
  inherits: base
  table_name: Transactor
  enum_mapper:
    # source: https://www.pa.gov/agencies/dos/resources/voting-and-elections-resources/campaign-finance-resources/technical-specifications-for-electronic-filing-of-campaign-expen.html#accordion-6a5fc1b7ea-item-8245f60064
    election_result--election--office_sought:
      STH: State Representative
      STS: State Senator
      GOV: Governor
      LTG: Lieutenant Governor
      ATT: Attorney General
      AUD: Auditor General
      TRE: State Treasurer
      SPM: Supreme Court Justice
      SPR: Judge # superior
      CCJ: Judge # commonwealth
      CPJ: Judge # common pleas
      CPJA: Judge # unlisted
      MCJ: Judge # municipal
      TCJ: Judge # traffic
      PH1: Mayor # philly
      PH2: District Attorney # philly
      PH3: Misc. City # City Controller, philly
      PH4: City Council # philly
      PH5: Misc. City # commissioner, philly
      PH6: Misc. City # register of wills, philly
      PH7: Misc. City # clerk of quarter sessions, philly

    transactor_type:
      "1": Candidate
      "2": Committee
      "3": Unknown # lobbyist, could be pac or ind

    party:
      DEM: Democratic Party
      REP: Republican Party
      CST: Constitutional Party
      LIB: Libertarian Party
      REF: Reform Party
      OTH: Party Described as Other by State

  column_details:
    - raw_name: CampaignFinanceID
      type: str

    - raw_name: FILERID
      type: str
      standard_name: id

    - raw_name: EYEAR
      type: Int16
      standard_name: election_result--election--year

    - raw_name: SubmittedDate
      type: str

    - raw_name: CYCLE
      type: Int8

    - raw_name: AMMEND
      type: str
      notes: bool

    - raw_name: TERMINATE
      type: str
      notes: bool

    - raw_name: FILERTYPE
      type: str
      standard_name: transactor_type
      enum: transactor_type
      notes: "TODO: enum?"

    - raw_name: FILERNAME
      type: str
      standard_name: full_name

    - raw_name: OFFICE
      type: str
      standard_name: election_result--election--office_sought
      enum: office_sought

    - raw_name: DISTRICT
      type: str
      standard_name: election_result--election--district

    - raw_name: PARTY
      type: str
      standard_name: party

    - raw_name: ADDRESS1
      type: str
      standard_name: address--line_1

    - raw_name: ADDRESS2
      type: str
      standard_name: address--line_2

    - raw_name: CITY
      type: str
      standard_name: address--city

    - raw_name: STATE
      type: str
      standard_name: address--state

    - raw_name: ZIPCODE
      type: str
      standard_name: address--zipcode

    - raw_name: COUNTY
      type: str
      standard_name: address--county

    - raw_name: PHONE
      type: str
      standard_name: phone_number

    - raw_name: BEGINNING
      type: Float32

    - raw_name: MONETARY
      type: Float32

    - raw_name: INKIND
      type: Float32
  duplicate_columns:
    reported_state: 
      - election_result--election--state

filer_through_2022:
  inherits: filer
  path_pattern: "(?i)^(19[0-9][0-9]|20[0-1][0-9]|2020|2021)/filer.*\\.txt$"
  column_order:
    - FILERID
    - EYEAR
    - CYCLE
    - AMMEND
    - TERMINATE
    - FILERTYPE
    - FILERNAME
    - OFFICE
    - DISTRICT
    - PARTY
    - ADDRESS1
    - ADDRESS2
    - CITY
    - STATE
    - ZIPCODE
    - COUNTY
    - PHONE
    - BEGINNING
    - MONETARY
    - INKIND


filer_post_2023:
  inherits: filer
  path_pattern: "(?i)^(?:20(?:2[4-9]|[3-9]\\d))/filer.*\\.txt$"

filer_2023:
  inherits: filer
  read_csv_params:
    sep: ","
    encoding: latin-1
    on_bad_lines: warn
    header: 0
  path_pattern: "(?i)^2023/filer.*\\.txt$"



expense:
  inherits: base
  table_name: Transaction
  column_details:
    - raw_name: CampaignFinanceID
      type: str

    - raw_name: FILERID
      type: str
      standard_name: donor_id

    - raw_name: EYEAR
      type: Int16
      standard_name: reported_election_year

    - raw_name: SubmittedDate
      type: str

    - raw_name: CYCLE
      type: Int16

    - raw_name: EXPNAME
      type: str
      standard_name: recipient--full_name

    - raw_name: ADDRESS1
      type: str
      standard_name: recipient--address--line_1

    - raw_name: ADDRESS2
      type: str
      standard_name: recipient--address--line_2

    - raw_name: CITY
      type: str
      standard_name: recipient--address--city

    - raw_name: STATE
      type: str
      standard_name: recipient--address--state

    - raw_name: ZIPCODE
      type: str
      standard_name: recipient--address--zipcode

    - raw_name: EXPDATE
      type: str
      date_format: "%Y%m%d"
      standard_name: date

    - raw_name: EXPAMT
      type: Float32
      standard_name: amount

    - raw_name: EXPDESC
      type: str
      standard_name: description

expense_through_2022:
  inherits: expense
  path_pattern: "(?i)^(19[0-9][0-9]|20[0-1][0-9]|2020|2021)/expense.*\\.txt$"
  column_order:
    - FILERID
    - EYEAR
    - CYCLE
    - EXPNAME
    - ADDRESS1
    - ADDRESS2
    - CITY
    - STATE
    - ZIPCODE
    - EXPDATE
    - EXPAMT
    - EXPDESC

expense_post_2023:
  inherits: expense
  path_pattern: "(?i)^(?:20(?:2[4-9]|[3-9]\\d))/expense.*\\.txt$"

expense_2023:
  inherits: expense
  read_csv_params:
    sep: ","
    encoding: latin-1
    on_bad_lines: warn
    header: 0
  path_pattern: "(?i)^2023/expense.*\\.txt$"
